### ISSUE TITLE
Still Not working on mobile

### ISSUE THREAD

**Issue by bearded-avenger** [WordPressDemo/WP-Demo#14]
Creating a new issue here hoping I'll get a response to the non-reponse here:

https://github.com/WordPressDemo/WP-Demo/

We are getting several reports of this still not working on mobile, and the X button to close out does nothing on iOS.

**Comment by dovy** [comment]
@bearded-avenger Please Skype me: DovyDigital or GChat me: info@simplerain.com

My twins have been in and out of the hospital the last 8 weeks. I've been a bit tied. Before they were born I tried it on my iPhone and it seemed to work. 

I'll gladly help you. Just add me and we'll chat about specifics.

**Comment by bfintal** [comment]
I've added more optimizations for mobile

**Comment by bfintal** [comment]
Mobile fixes:
- removed labels when screen is small + larger product switcher on mobile + no longer forces a close on the preview bar when mobile is detected + removed mobile detection code
- Better product carousel. Now uses Owl Carousel, auto adjusts & is touch/drag enabled
- Fixed sticky headers for mobile
- Added fastclick
- Fixed bug where in iOS devices, the contents go past the iframe width. This should work since we always have the same origin

**Comment by bearded-avenger** [comment]
much appreciated

**Comment by bfintal** [comment]
You can see it in action here: http://demos.gambit.ph/parallax We're just testing now :)

**Comment by bearded-avenger** [comment]
Good stuff. Upon visiting your demo link above, the close button still doesn't seem to close out the preview bar. Testing on iPhone 5S running iOS8 and an iPad Mini running iOS7.

Also, just a suggestion, ideally the buttons to preview the site in responsive modes wouldn't appear on iOS devices.

**Comment by bfintal** [comment]
For the close button, I don't know why it's not working on your end, or why it's working on mine :confused: I tried on my iPhone 5, iOS 7.1.2 on both Safari & Chrome and the close button is working for me. Haven't gotten iOS 8 though, although I don't think that's much of a difference.

What happens when you click/tap on it? The behavior should be that it directs you to the URL without the `?preview` appended, but now instead of redirecting you back to the one with `?preview`, it should remain on that page.

Good suggestion :)

**Comment by bfintal** [comment]
Now detecting touch and screen size to remove the resolution buttons for mobile devices. It isn't uploaded to the demo site.

Finally got iOS 8. It still works in both Safari & Chrome in mine.
